Add two new survey ETLs for Desktop and Mobile CSAT surveys
mozilla/bigquery-etl pull request #3096
Opened 2022-07-15 16:02 UTC by birdsarah

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

2022-07-15 23:41 UTC, sean-rose requested changes
- You'll need to run `bqetl dag generate` locally and check in the resulting changes (that's why the "verify-dags-up-to-date" CI step failed).
- After this PR is merged, how far back should those surveys be backfilled? (e.g. when were they created)

2022-07-16 21:38 UTC, birdsarah commented
> After this PR is merged, how far back should those surveys be backfilled? (e.g. when were they created)

Not too long - June 1, 2022

2022-07-16 21:58 UTC, birdsarah commented
@sean-rose when i ran `bqetl dag generate` locally it also updated `dags/bqetl_unified.py` but when i committed that the tests failed so i uncommitted it. Just thought I'd mention it though.

2022-07-18 22:40 UTC, sean-rose approved these changes

2022-07-18 22:47 UTC, merged