feat(DENG-582): Replaced init.sql for fxa_users_first_seen_v1 with schema.yaml
mozilla/bigquery-etl pull request #3466
Opened 2022-12-16 13:47 UTC by kik-kik

# feat(DENG-582): Replaced init.sql for fxa_users_first_seen_v1 with schema.yaml

Field descriptions have also been added.

2022-12-16 19:45 UTC, lucia-vargas-a commented
I wonder if `client_id` is the commonly queried column or we should add a  `sample_id` for clustering and to facilitate the queries?

2022-12-23 14:31 UTC, gkabbz approved these changes

2023-01-06 13:25 UTC, fbertsch requested changes
This should be merged with the other PR, https://github.com/mozilla/bigquery-etl/pull/3464, which changes the schema of `query.sql`.

2023-01-06 14:46 UTC, kik-kik commented
As suggested by @fbertsch, moved these changes over to PR#3464.

2023-01-06 14:46 UTC, closed without merging