Add change control to the request payload tables
mozilla/bigquery-etl pull request #3833
Opened 2023-05-22 20:43 UTC by alekhyamoz

Relates to https://mozilla-hub.atlassian.net/browse/RS-698

TL;DR The request payload tables should be changed without the necessary approvals.
The primary owners are Wil Stuckey and Rebecca BurWei and one of their approval is required to make changes to the ETL logic.
Tagging both of them as reviewers in this PR for awareness

2023-05-23 17:06 UTC, lucia-vargas-a requested changes

2023-05-23 17:06 UTC, lucia-vargas-a commented on sql/moz-fx-data-shared-prod/contextual_services_derived/request_payload_suggest_v2/metadata.yaml
>    schedule: daily
```suggestion
  schedule: daily
  change_controlled: true
```

2023-05-23 17:06 UTC, lucia-vargas-a commented on sql/moz-fx-data-shared-prod/contextual_services_derived/request_payload_tiles_v2/metadata.yaml
>    schedule: daily
```suggestion
  schedule: daily
  change_controlled: true
```

2023-05-25 18:57 UTC, alekhyamoz commented on sql/moz-fx-data-shared-prod/contextual_services_derived/request_payload_suggest_v2/metadata.yaml
> -  owner1: skahmann
so the owners listed here i.e. Sydney and I are just dag owners and are not part of the `request_payload_reviewers`. Wil and Rebecca would be the change control decision makers

2023-05-26 10:56 UTC, lucia-vargas-a approved these changes
The change control implementation LGTM! The only question is about the duplicated owners, if it's necessary.

2023-05-26 14:37 UTC, merged