feat(): updated fenix.firefox_android_clients view to use v2 of the corresponding table
mozilla/bigquery-etl pull request #4562
Opened 2023-11-14 14:27 UTC by kik-kik

# feat(): updated fenix.firefox_android_clients view to use v2 of the corresponding table

2023-11-27 14:43 UTC, lucia-vargas-a requested changes
The tests folder and schema file need to be renamed to:
- Folder /Users/lucia/Code/bigquery-etl/tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v2
- Table schema in tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/moz-fx-data-shared-prod.fenix_derived.firefox_android_clients_v1.schema.json to  ...firefox_android_clients_v2.schema.json

2023-11-27 14:47 UTC, lucia-vargas-a commented
> The tests folder and schema file need to be renamed to:
> 
>     * Folder /Users/lucia/Code/bigquery-etl/tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v2
> 
>     * Table schema in tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/moz-fx-data-shared-prod.fenix_derived.firefox_android_clients_v1.schema.json to  ...firefox_android_clients_v2.schema.json

+ renaming all files that are named v1 to v2 inside each test.

2023-11-27 14:54 UTC, kik-kik commented
@lucia-vargas-a Does that resolve the issue? But I'm a little bit puzzled by why this matters, surely those tests are for v1 and since no changes to v1 are made these tests should work as normal?

2023-11-27 14:59 UTC, lucia-vargas-a commented
The query has changed from the v1 to v2. In v1 it was calling the [upstream from shared-prod](https://github.com/mozilla/bigquery-etl/blob/f635adc06987ba8781fc7d7568eb3e1d1106edf1/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/query.sql#L23). In v2 it has changed to [query mozdata](https://github.com/mozilla/bigquery-etl/blob/f635adc06987ba8781fc7d7568eb3e1d1106edf1/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v2/query.sql#L18). This results in tests failures and potentially different data (if there is additional logic or different sources referenced in either) o solve the conflict there are 2 options:
- Update the tests to remove the project_id only if the views in shared-prod and mozdata are equal
- Update the query to continue using the shared-prod tables as in v1.

2023-11-27 15:05 UTC, lucia-vargas-a commented
Table fenix.baseline_clients_first_seen needs to be added to the tests. V1 was using clients_daily.

2023-11-28 14:54 UTC, kik-kik commented
V2 is proving too problematic to productionise given the benefit. For now we will stick to v1 of the clients table and use it as the base for producing retention models.

2023-11-28 14:54 UTC, closed without merging