Add distribution_id to feature_usage_events_v1
mozilla/bigquery-etl pull request #6277
Opened 2024-09-30 21:01 UTC by m-d-bowerman

## Description

This PR adds the client distribution_id. This is necessary to count app push notification events and set to default events to support mobile distribution deals.

2024-10-02 17:02 UTC, kik-kik commented on sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_events_v1/query.sql
> +  distribution_id,
this `distribution_id` is a bit hidden right now among all the aggregations. Would it make sense to make it live just under the `is_default_browser`? We could keep all the grouping keys together this way and the query easier to read.

2024-10-02 17:02 UTC, kik-kik commented on sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_events_v1/query.sql
> +    ) AS top_sites_contile_impression
```suggestion
    ) AS top_sites_contile_impression,
```

2024-10-02 17:04 UTC, kik-kik commented on sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_events_v1/query.sql
> +    distribution_id
```suggestion
    distribution_id,
```

2024-10-02 17:04 UTC, kik-kik approved these changes
r+wc

Just some small comments. Please read through before merging.

2024-10-02 17:07 UTC, kik-kik commented
One thing we should think about, since we're adding a new grouping value should we recompute partitions that were generated prior to when we merge this change? Or alternatively, should we have a note in the metadata.yaml inside the description indicating that this data was only added after certain date to minimise the risk of confusion when trying to use this data?

2024-10-02 17:09 UTC, m-d-bowerman commented
> One thing we should think about, since we're adding a new grouping value should we recompute partitions that were generated prior to when we merge this change? Or alternatively, should we have a note in the metadata.yaml inside the description indicating that this data was only added after certain date to minimise the risk of confusion when trying to use this data?

Yes, I'll do some validation before merging this and update the metadata.

2024-10-08 09:55 UTC, kik-kik commented
@m-d-bowerman Are we good to merge this?

2024-10-08 10:43 UTC, kik-kik requested changes
Is this the correct events that we want to track?

2024-10-08 12:31 UTC, kik-kik approved these changes

2024-10-08 14:16 UTC, merged